[package]
name = "derive-entity"
version = "0.1.1"
authors = ["Dr. David A. Kunz <kunz.david.alexander@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
entity = { path = "../" }

[dependencies]
syn = "2.0"
quote = "1.0"
