name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Start postgres
      run: docker run -d --rm -p 5432:5432 -e "POSTGRES_PASSWORD=postgres" --name pg postgres:15
    - name: Run tests
      run: cargo test --verbose
    - name: Stop postgres
      run: docker stop pg
