name: Rust Lint

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --all-features
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose
